# ===========================================

minio:
  endpoint: '47.99.52.9:9000'
  access_key: 'admin'
  secret_key: 'Aa123456.'
  secure: false  # Httpsåè®®

# ===========================================

buckets:
  - name: 'test1'
    bucket_dir: "test1/"  # å­˜å‚¨æ¡¶ä¸­çš„ä¸€ä¸ªè·¯å¾„

  - name: 'zyb-v3'
    bucket_dir: "zuoyebang-SQ-3/"  # å­˜å‚¨æ¡¶ä¸­çš„ä¸€ä¸ªè·¯å¾„

# ===========================================

local:
  directory: 'D:/bucket'  # å®¢æˆ·ç«¯: æ­¤æ–‡ä»¶å¤¹å¿…é¡»å­˜åœ¨
  local_dir: 'D:/bucket/{bucket_name}/{bucket_dir}'  # æœ¬åœ°ä½ç½®æ¨¡æ¿ï¼Œæ ¹æ®å­˜å‚¨æ¡¶åç§°åŠ¨æ€ç”Ÿæˆ

  # ===========================================

settings:
  max_workers: 30,  # è¿›ç¨‹ï¼ˆæœªå¯ç”¨)

# ===========================================



#14:30:22 | INFO     | ğŸ”„ å¼€å§‹åŒæ­¥æ–‡ä»¶å¤¹ [zuoyebang-SQ-3/] å…± 35 ä¸ªæ–‡ä»¶
#14:30:25 | DEBUG    | ğŸ“¥ ä¸‹è½½è¿›åº¦ | 352_20_part... | 45.6% | 102MB/223MB
#14:30:27 | SUCCESS  | âœ… å®Œæˆä¸‹è½½ | 352_20_part1.xlsx
#14:30:28 | ERROR    | ğŸš¨ 352_20_part2.xlsx âŒ è¿æ¥è¶…æ—¶
#14:31:02 | INFO     | ğŸ“¦ æ–‡ä»¶å¤¹åŒæ­¥å®Œæˆ | æˆåŠŸ: 33/35
#ğŸ“
#ğŸš€